name: gwsc-production-deploy
runs-on: unbuntu-latest
steps:
- name: gwsc-deploy-key
  uses: shimataro/ssh-key-action@v2
  with:
    key: ${{ secrets.GIT_ZEKE_SSH }}
    known_hosts: 'placeholder-for-0-errors'
    if_key_exists: fail
- name: add known hosts
  run: ssh-keyscan -p ${{ secrets.GIT_ZEKE_PORT }} -H ${{ secrets.GIT_ZEKE_HOST }} >> ~/.ssh/known_hosts
- name: gwsc-rysnc
    on:
    push:
      branches:
      - prod
    jobs:
      write-to-console:
      runs-on: ubuntu-latest
    steps:
      - name: gwsc-rsync-copy
    run: rsync -aPvz -e --exclude=img/.DS_Store --exclude=robots.txt ./build/ "ssh -p ${{ secrets.GIT_ZEKE_PORT }}" --delete ${{ secrets.ZEKE_USER }}@${{ secrets.ZEKE_HOST }}:/var/www/gwsc.net/html/_test/ --dry-run